liip_imagine:
  # configure resolvers
  resolvers:
    # setup the default resolver
    default:
      # use the default web path
      web_path: ~

  # your filter sets are defined here
  filter_sets:
    # use the default cache configuration
    cache: ~

    # the name of the "filter set"
    figure_thumb:
      # adjust the image quality to 75%
      quality: 75

      # list of transformations to apply (the "filters")
      filters:
        # create a thumbnail: set size to 250x120 and use the "outbound" mode
        # to crop the image when the size ratio of the input differs
        thumbnail: { size: [250, 120], mode: outbound }

    # the name of the "filter set"
    avatar_thumb:
      # adjust the image quality to 75%
      quality: 75

      # list of transformations to apply (the "filters")
      filters:
        # create a thumbnail: set size to 200x200 and use the "outbound" mode
        # to crop the image when the size ratio of the input differs
        thumbnail: { size: [200, 200], mode: outbound }
